### PR TITLE
Webkit -Support

### PR DESCRIPTION
**Pull request by lytico**
introduce Webkit - Support

using definitions from

https://github.com/GSharpKit/webkitgtk3-sharp

### CODE REVIEW

**Comment by lytico** [comment]
> Are you wrapping deprecated Webkit1 or current Webkit2 API?

@zii-dmg i am wrapping libwebkitgtk-3.0.dll, that is wrapping WebKit API-Version 3.0

**Comment by lytico** [comment]
>WebkitGTK doesn't support Windows, should make something like if (IsWindows) create label "Sorry, WebView is not supported on Windows".

@zii-dmg see: https://github.com/GtkSharp/GtkSharp/pull/270

**Comment by zii-dmg** [comment]
According to answers from [stackoverflow](https://stackoverflow.com/questions/19692818/webkitgtk-gtk2-gtk3) I think this is webkit1 for gtk3. Better than nothing, but last answer on stackoverflow from 2018 year is:

> The ONLY Linux port of WebKit is WebKit2-GTK3. All the others are dead and do not receive security updates, which makes them trivial targets for hackers. If you have an application that depends on other versions of WebKit on Linux, uninstall it. End of story.

**Comment by lytico** [comment]
so it should target libwebkit2gtk-3.0 to get webkit2.

problem: where do i get the WebkitGtkSharp.metadata et al?

**Comment by zii-dmg** [comment]
This conversation may help - https://github.com/GtkSharp/GtkSharp/issues/168#issuecomment-645625794.
As I understand SomeLib.xml was generated by old mono tool - gapi parser that parses C headers. No one generated xml for new libs like webkit2.
SomeLib.metadata is only to fix errors in xml.

**Comment by lytico** [comment]
> As I understand SomeLib.xml was generated by old mono tool - gapi parser that parses C headers

yes, some crude meson stuff. i tried this already some time ago, never got it to work.

**Comment by zii-dmg** [comment]
There is manual wrapper for webkit2 in Eto.Forms:
https://github.com/picoe/Eto/blob/develop/src/Eto.Gtk/NativeMethods.cs
https://github.com/picoe/Eto/blob/develop/src/Eto.Gtk/Forms/Controls/WebKit2WebViewHandler.cs

**Comment by zii-dmg** [comment]
I just created .NET 5 console project, deleted program.cs, added https://github.com/GtkSharp/GtkSharp/blob/develop/Source/OldStuff/parser/gapi-parser.cs and it compiled.
Code is calling gapi_pp.pl, gapi2xml.pl (perl) so should be run from linux + perl + this pl scripts. I don't tried to run.

**Comment by harry-cpp** [comment]
> There is manual wrapper for webkit2 in Eto.Forms:
> https://github.com/picoe/Eto/blob/develop/src/Eto.Gtk/NativeMethods.cs
> https://github.com/picoe/Eto/blob/develop/src/Eto.Gtk/Forms/Controls/WebKit2WebViewHandler.cs

I did that in a time before time :D
https://github.com/picoe/Eto/pull/747

> I just created .NET 5 console project, deleted program.cs, added https://github.com/GtkSharp/GtkSharp/blob/develop/Source/OldStuff/parser/gapi-parser.cs and it compiled.
> Code is calling gapi_pp.pl, gapi2xml.pl (perl) so should be run from linux + perl + this pl scripts. I don't tried to run.

Yep, you also need to install an extra perl lib if my memory serves me correctly (and ofc the source of what you want to generate the metadata for).

**Comment by lytico** [comment]
i managed to get an api definition, but it doesn't compile.

see this pr: https://github.com/GtkSharp/GtkSharp/pull/271

**Comment by zii-dmg** [comment]
What I have archived: [GapiParser.zip](https://github.com/GtkSharp/GtkSharp/files/6843650/GapiParser.zip)
Files in bin `webkit2gtk.raw_c`, `webkit2gtk.raw_cpp` are result of gapi-parser.
cpp is version for that I changed .c processing to .cpp (code not in zip, zip have .c processing).
I modified .cs from `system("xxx.pl")` to `system("./xxx.pl")`
I modified .pl to remove some WEBKIT macros from input lines (or have errors).
For perl need to install package "libxml-libxml-perl" (debian based distrib).
Parser don't see signals, properties, child properties.

I 99% sure it will not generate working C# but you can try.

**Comment by hol430** [comment]
I see that you guys have largely moved past this by now, but in case it's helpful to anyone in the future trying to figure this stuff out, [this page](https://www.mono-project.com/docs/gui/gtksharp/gapi/) from the mono docs has been useful to me, despite being largely aimed at gtk2.

**Comment by lytico** [comment]
closed in favor of #271

**Pull request closed without merging**
