### PR TITLE
[WIP] Bundle Windows libraries

### PR DESCRIPTION
**Pull request by cra0zy**

### CODE REVIEW

**Comment by Nihlus** [comment]
Nice. Don't forget to include some of the external files, like compiled GSettings.

**Comment by cra0zy** [comment]
> Nice. Don't forget to include some of the external files, like compiled GSettings.

Of course. Besides the schemas, do you see anything else that I might be missing right now?

**Comment by Nihlus** [comment]
A default icon theme would be good.

**Comment by Urgau** [comment]
> I need to rethink the way of bundling the libraries...

Is it done ? Can this pull request be merged ?

**Comment by AlseinX** [comment]
Is there any news on it?

**Comment by cra0zy** [comment]
Nope, I know how to get the needed set of libraries but I don't know of a good way to distribute them that is consistent.

**Comment by AlseinX** [comment]
The GtkSharp.Win32 package outputs the dll files to the build output folder, but GtkSharp does not seem to use it. I don't know how GtkSharp loads the native libraries, but would AssemblyLoadContext help?

**Pull request closed without merging**
