### PR TITLE
Improve integration with C#

### PR DESCRIPTION
**Pull request by badcel**
Add interfaces for some types: IObject (GLib.Object), IWidget (Gtk.Widget), IButton (Gtk.Button). 

_This allows to develop with GTK and MVVM / Test Driven Development in mind. I only added the interfaces for properties needed in my own project. This could / should be extended as it does not add additional logic, but allows library users to effectively Mock objects._

Add support for INotifyPropertyChanged to GLib.Object.

_This allows every C# code to register for INotifyPropertyChanged on GLib.Object. The signals from GTK are automatically converted to the corresponding property names in GtkSharp._

### CODE REVIEW

**Comment by badcel** [comment]
What do you think of this changes?

My project is nearing its first public release. Without this changes I'm not able to release it. So if you need to choose between my pull requests, please prefer this one.

**Comment by cra0zy** [comment]
A bit of a late comment, I would be fine with adding interfaces, however only for GtkSharp 4, as I plan to break compatibility with its release anyways.

If you wanna add it for GtkSharp 3, you would need to fix the tools to generate interfaces for all the classes they spew out.

**Comment by badcel** [comment]
I'm fine with adding it to GTK4.

**Comment by gavr123456789** [comment]
Any news? Really need this

**Comment by badcel** [comment]
I'm not going to push more code to this PR. If you want you can continue the work.

**Comment by miegir** [comment]
Perhaps I'm too late but I want to add my opinion here. Are interfaces like IButton really needed in base library? If you need such interface in your library, you can create interface yourself and write a simple adapter of GTK button to your interface. You can modify your private interface and implementation (adapter) when you want. But once public interface is added to the base library, every change in it is breaking change, because when method is added to this interface, every existing implementation in third party library will be broken because it not implements new method. So it can pe pain for the base library developer and will lead to creating IButton2, IButton3 interfaces and so on. But the purpose of all that is unclear. I hope that this PR is still not merged because of this exact reason. Implementing INotifyPropertyChanged, on the other hand, can be useful.

<details>
  <summary>Some concrete example</summary>

``` C#
interface IMyButton
{
    bool Sensitive { get; set;}
}

class MyButtonAdapter : IMyButton
{
    private readonly Button button;

    public MyButtonAdapter(Button button)
    {
        this.button = button;
    }

    public Sensitive => button.Sensitive;
}
```
And now you can use `new MyButtonAdapter(button)` wherever you need `IMyButton`.
</details>

**Pull request closed without merging**
