### PR TITLE
feat: GtkSharp net6 workload

### LINKED ISSUE #349: GtkSharp net6 Workload
GtkSharp should have a net6-workload.

That's needed for projects using GtkSharp, eg. the (somewhen) upcoming Maui.Gtk

What is that?: 
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-install
https://github.com/dotnet/designs/blob/main/accepted/2020/workloads/workloads.md

related issues: 
https://github.com/GtkSharp/GtkSharp/issues/290
see also: https://github.com/GtkSharp/Dependencies

### PR DESCRIPTION
**Pull request by trungnt2910**
A .NET 6 Workload for GtkSharp. Should close #349.

## What it can do:
Allow projects like this:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-gtk</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="**\*.glade" />
    <EmbeddedResource Include="**\*.glade">
      <LogicalName>%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
```
to build, run and publish correctly, with a unique `net6.0-gtk` TFM and no package references.

## Some changes I made:
- Added a strong name key. The `CreateFrameworkListFile` target from `Microsoft.DotNet.SharedFramework.Sdk`, used to generate reference and runtime library packs, requires input assemblies to be signed, as it checks for a non-null `PublicKeyToken`. Furthermore, other .NET workload packs I know (Tizen, Xamarin,...) also have strong names.
- Edited a few `Directory.Build.props` file, so that the workloads and the libraries can share a few build variables. This makes it easier for workload build scripts to locate output libraries for frameworks.

I hope this pull request can be considered. If there's anything in this PR against the project's rules, please let me know as soon as possible so that I can quickly fix the problem.

### CODE REVIEW

**Comment by trungnt2910** [comment]
A question about templates:
Other workloads also provide templates for the .NET Sdk.
GtkSharp already has templates, however, these use the `net6.0` TFM and references GtkSharp as a NuGet package.
Should I modify these files directly in this PR and include the existing templates in the workload, or make a separate workload template pack?

**Comment by lytico** [comment]
i would prefer separate workload template pack

**Comment by trungnt2910** [comment]
> i would prefer separate workload template pack

Done. I've added the workload packs for the three languages.
The templates in the workload pack:
- Have `Workload` in their package names.
- Use the target framework `net6.0-gtk` instead of `net6.0` and do not reference the `GtkSharp` package.
- Allow creating applications using `dotnet new gtk` instead of `dotnet new gtkapp` (to ensure parity with other workloads,  such as `dotnet new macos` and `dotnet new android`, as well as avoiding clashes with the existing `gtkapp` templates).

**Comment by thomiel** [comment]
We had some testing of the .NET 6 workload at #maui-linux:matrix.org and it proved ok to use, although there seems to be an issue with the templates on Linux that is still under investigation. This is how you would test it (including a hack to make the templates appear) on Ubuntu 22.04:

    # install dotnet 6
    sudo apt-get update; \
    sudo apt-get install -y apt-transport-https && \
    sudo apt-get update && \
    sudo apt-get install -y dotnet-sdk-6.0

    # add keys
    wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb

    # install gtksharp with dotnet 6 support
    git clone https://github.com/trungnt2910/GtkSharp.git
    cd GtkSharp
    sudo dotnet tool restore
    sudo dotnet cake --BuildTarget=InstallWorkload 

    # hack for making the templates visible in dotnet new
    sudo cp /usr/share/dotnet/template-packs/* /usr/share/dotnet/templates/6.0.5

    # install gtk
    sudo apt-get install libgtk-3-0

    # test gtk template
    cd ..
    mkdir gtksharptest
    cd gtksharptest
    dotnet new gtk
    dotnet run

Having this included in an official release would be useful for our effort to establish Linux support for .NET MAUI (Multi-platform App UI).

**Comment by harry-cpp** [comment]
Well, I'm low on time, so its time to merge first and ask questions later :D

Thanks @trungnt2910 !

**Comment by knocte** [comment]
@harry-cpp AFAIU, there's no version in nuget that has the feature yet. Why hasn't there been a release recently?

**Comment by trungnt2910** [comment]
You might want to upvote #355.

**Pull request merged**
