### PR TITLE
FuncLoader: Add support for unknown Unix

### PR DESCRIPTION
**Pull request by trungnt2910**
When the operating system is unknown, try to find `dlsym` and `dlopen` in `libc` instead. .NET will resolve this name to the correct system library.

### CODE REVIEW

**Comment by trungnt2910** [comment]
Also added a condition to the CI to check for `develop` branch and the `push` event.

Otherwise, publishing beta packages would not make much sense.

**Comment by lytico** [comment]
> Also added a condition to the CI to check for `develop` branch and the `push` event.
> 
> Otherwise, publishing beta packages would not make much sense.

Please, don't mix distinct problems in one PR.
Open extra PR for CI stuff.
Thanks!

**Comment by trungnt2910** [comment]
I added this commit here because otherwise CI would fail for the PR.

**Comment by lytico** [comment]
> I added this commit here because otherwise CI would fail for the PR.

yes, i confirm, all CI's on pulls fail at the moment.
so, your (future) PR concerning CI will be highly welcome.
Nethertheless, it's an CI problem, and not a FuncLoader problem, and maybe gets some other people involved.

**Comment by trungnt2910** [comment]
Done. Removed the second commit.

**Comment by lytico** [comment]
thanks!

**Comment by lytico** [comment]
seems that this is also related to 
https://github.com/GtkSharp/GtkSharp/issues/394
is this solved then, or needs extra Code in funcloader?

**Comment by lytico** [comment]
Remark on FreeBSD: they discussed this here: https://github.com/sec/dotnet-core-freebsd-source-build/issues/18#issuecomment-1480338791

**Comment by trungnt2910** [comment]
> seems that this is also related to 
> https://github.com/GtkSharp/GtkSharp/issues/394
> is this solved then, or needs extra Code in funcloader?

I don't know, can't test because I don't have a FreeBSD machine.

`libc` would be a safe cross-platform choice because .NET handles [`libc`](https://github.com/dotnet/runtime/blob/8c51f019880e620fc59299024518fb8d002033b3/src/coreclr/pal/src/loader/module.cpp#L518C1-L543C2) specially for `DllImport`.

`dlopen` and `dlsym` are [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/functions/dlopen.html) functions so many OSes would put them in the standard C library. [FreeBSD](https://man.freebsd.org/cgi/man.cgi?query=dlopen&sektion=3&format=html) also seems to do so, so this PR theoretically could solve the mentioned #394.

**Comment by lytico** [comment]
ok, i see. 
so let's discuss the FreeBsd-Story in an extra PR.

**Comment by lytico** [comment]
what "unknown unix" was your usecase to be engaged in this PR?

**Comment by trungnt2910** [comment]
I'm trying to port GtkSharp to run on [Haiku OS](http://haiku-os.org/).

The OS is currently not officially supported by .NET, though I have ported the runtime and have builds [here](https://github.com/trungnt2910/dotnet-builds), and PRs to the official repo are pending.

GtkSharp itself has been tested and is confirmed to [work](https://discuss.haiku-os.org/t/gsoc-2023-net-port/13237/49).

**Comment by lytico** [comment]
tested on ubuntu 20.04 derivate, builds and samples run without error

**Comment by lytico** [comment]
thanks!

**Pull request merged**
