### PR TITLE
Sign the DLL files

### PR DESCRIPTION
**Pull request by mikkeljohnsen**
This will sign the assemblies files.

### CODE REVIEW

**Comment by the-black-wolf** [comment]
You do not have to switch build platform, just switch to .net core 3 preview (later to final). It supports assembly signing. I just signed a sample app for proof.

image. 


Though I see no reason why you would want to, it serves no purpose any more given that sandboxing is rather dead. Signing assemblies forces you into very strict versioning process with no clear benefits.

**Comment by cra0zy** [comment]
@mikkeljohnsen I have switched the build system to azure pipelines, try rebasing your branch now.

**Comment by mikkeljohnsen** [comment]
This is not a issue for us anymore.

**Comment by ermshiperete** [comment]
> Though I see no reason why you would want to, it serves no purpose any more given that sandboxing is rather dead. Signing assemblies forces you into very strict versioning process with no clear benefits.

For a library you want to sign the assembly for exactly that reason. If a consumer of this package for whatever reason want to sign their assembly, all the dependencies have to be signed. So it is better (i.e. more useful) for a library to be signed even though there are no benefits nowadays. On the other hand the cost of signing the library is minimal.

Signing the library doesn't constrain the users of the nuget package in any way - they can use it in a signed or an unsigned project. On the other hand, an unsigned library can only be used in an unsigned project.

**Pull request closed without merging**
