### PR TITLE
Fixed StackUnbalancedException

### PR DESCRIPTION
**Pull request by mikel785**
Hello guys:

While using gtk sharp on windows with x86 process architecture had a lot of StackUnbalanced exceptions with 32bit gtk3 binaries from MSYS2.

The problem is that calling convention declaration is missing on generated delegates for native gtk3 api.

I suppose that more elegant way to solve that problem can take place but it works.

### CODE REVIEW

**Comment by cra0zy** [comment]
The way you make it so the project can be compiled with both .NET Core and .NET Framework is by doing something like:
```
<TargetFrameworks>net471;netcoreapp2.0</TargetFrameworks>
```

I'll merge ea6daa7 and b4e163e as soon as I can.

**Comment by mikel785** [comment]
Ок than. This solution to use attributes seems to be a crutch more than a silver bullet.

It seems that some diggings in FuncLoader can achieve the same results without using attributes.

```
    public static T LoadFunction<T>(IntPtr procaddress)
    {
        if (procaddress == IntPtr.Zero)
            return default(T);

        return Marshal.GetDelegateForFunctionPointer<T>(procaddress);
    }
```

We just need some kind of calling convention adopted in that point `Marshal.GetDelegateForFunctionPointer<T>(procaddress);`.

But there is a lack of method Marshal.GetDelegateForFunctionPointer<T>(procaddress, callingConvention).

Let's take a break for a day or two.

**Comment by mikel785** [comment]
Hello. 
This solution is ok until project will be migrated to standard 2.1.
There is no any luck without attributes by now.

Please merge how it is.

**Comment by cra0zy** [comment]
The commits have been merged in #114, many thanks for the contribution!

**Pull request closed without merging**
