### PR TITLE
Use Marshal.GetFunctionPointerForDelegate<T>

### PR DESCRIPTION
**Pull request by kant2002**
This make code more trim friendly

Improve #300

### CODE REVIEW

**Comment by lytico** [comment]
i already took a look, but haven't time to test it more intense.

what i want to test is the behaviour of this, especially with  https://github.com/lytico/xwt/tree/lytico_gtksharp and https://github.com/jsuarezruiz/maui-linux/tree/main-linux. 

both of them make intense use of https://github.com/GtkSharp/GtkSharp/pull/301/files#diff-1dae5ee7d85315e364ff120a4d4f66812556444989eb595c6a9c98b3b3bfef39

remark: my engagement on GtkSharp is pure non commercial, and i need money from time to time. i'm buzy with a commercial project just now.

**Comment by kant2002** [comment]
I will try test links which you give to me. Do you test in NativeAOT context or as regular apps? 

I do understand that you do not own me support in any ways. If my overly enthusiastic passion to NativeAOT cause you the trouble, I deeply apologize.

**Comment by lytico** [comment]
>  cause you the trouble, I deeply apologize.

not at all. i just wanted to express that it tooks some time for me to find a free time slot in my time schedule & test it.

> I will try test links which you give to me. 

could be challenging for you, especially in the case of maui. for me it would be just an hour or so per project.

> Do you test in NativeAOT context or as regular apps

i'll test as regular apps for now.

**Comment by harry-cpp** [comment]
I am gonna go on a limb and say that the xwt crash has nothing to do with the changes you've made, these changes should be safe, if not, we can always revert.

Thanks @kant2002 !

**Pull request merged**
