### PR TITLE
Support style properties

### PR DESCRIPTION
**Pull request by zii-dmg**
Added support for style properties and marked some style properties in GtkSharp.metadata.

### CODE REVIEW

**Comment by zii-dmg** [comment]
Partially fixes #54.

**Comment by zii-dmg** [comment]
I just write `StyleGetProperty` instead of classic getter if property has `style="true"` attribute in api xml. Plus some checks for nullable structs (don't know if it corrent way). But now style properties that I marked is working and not throwing.

**Comment by lytico** [comment]
there are a lot of deprecated properties
they should be marked as obsolete

eg:
https://developer.gnome.org/gtk3/stable/GtkButton.html#GtkButton--s-child-displacement-x
https://developer.gnome.org/gtk3/stable/GtkButton.html#GtkButton--s-child-displacement-y

etc etc

**Comment by zii-dmg** [comment]
As I understand almost all style properties are deprecated in GTK but maybe they can be useful for some purposes, I don't know. Better obsolete not remove, although style properties wasn't working so no one is using it now.

Want me to add deprecated in metadata? (like `<attr path="/api/namespace/object[@cname='GtkButton']/property[@name='DefaultBorder']" name="deprecated">true</attr>`)

**Comment by lytico** [comment]
> Want me to add deprecated in metadata? (like <attr path="/api/namespace/object[@cname='GtkButton']/property[@name='DefaultBorder']" name="deprecated">true</attr>)

yes, would be nice!

**Comment by lytico** [comment]
thanks!

**Pull request merged**
