### PR TITLE
[glib] Fix `g_filename_[from|to]_utf8` signatures for 64 bits platforms

### PR DESCRIPTION
**Pull request by spouliot**
Fixes https://github.com/GtkSharp/GtkSharp/issues/345

### CODE REVIEW

**Comment by spouliot** [comment]
@lytico Do you want me to add the unit test for this ? There seems to be none in the repo (or I did not look hard enough)

**Comment by spouliot** [comment]
`StringToFilenamePtr` is not called from, at least directly, anywhere in the samples.
In fact nothing from `Marshaller` is called from the samples :(

**Comment by lytico** [comment]
tested on linux: Ubuntu 20.04 Kernel: 5.13.0-40-generic x86_64
tested on Windows 10

all tests ok

**Comment by lytico** [comment]
thanks!

**Pull request merged**
