### PR TITLE
Sign the DLL files

### PR DESCRIPTION
**Pull request by ermshiperete**
This is a follow-up of #75.

From a comment in #75:

> Though I see no reason why you would want to, it serves no purpose any more given that sandboxing is rather dead. Signing assemblies forces you into very strict versioning process with no clear benefits.

For a library you want to sign the assembly for exactly that reason. If a consumer of this package for whatever reason want to sign their assembly, all the dependencies have to be signed. So it is better (i.e. more useful) for a library to be signed even though there are no benefits nowadays. On the other hand the cost of signing the library is minimal.

Signing the library doesn't constrain the users of the nuget package in any way - they can use it in a signed or an unsigned project. On the other hand, an unsigned library can only be used in an unsigned project.

---
This change is [Reviewable](https://reviewable.io/reviews/gtksharp/gtksharp/139)

### CODE REVIEW

**Comment by VisualMelon** [comment]
Might I ask if there is any issue blocking this? It has been suggested that OxyPlot.Gtk could switch to this library, and the only outstanding issue we've found is the lack of signing (OxyPlot signed everything). (Issue at our end https://github.com/oxyplot/oxyplot-gtksharp/issues/9). I've tested with this branch and can confirm is resolves the problem.

**Comment by harry-cpp** [comment]
I need to modify the build bot to hide the key properly.

**Comment by VisualMelon** [comment]
The snk is just for identification. I don't think MS publish theirs (not checked), but generally open source projects do. See https://docs.microsoft.com/en-us/dotnet/standard/assembly/create-use-strong-named

> Do not rely on strong names for security. They provide a unique identity only.

With NET Core, some of this stuff has changed, and as far as I can tell it's becoming ever more obsolete, but still needed for compatibility with NET Framework.

**Comment by harry-cpp** [comment]
Sure then, I'll merge this! Thanks @VisualMelon @ermshiperete !

**Pull request merged**
