### PR TITLE
Added sourceview bindings

### LINKED ISSUE #168: Gtk SourceView Support
Hello, thanks for all the hard work you've put into this binding.

Would it be possible to add a binding to GtkSourceView to this lib? Would this lib be a good place to put that?

Could someone give me a high level overview of how to create a binding for SV myself?

Thank you!

### PR DESCRIPTION
**Pull request by hol430**
Only tested on linux so far. I've changed the sample project so that the sample code is displayed in a SourceView widget rather than a TextView. Couple questions:

- What is your current process for running gapi-parser to generate the *-api.xml files? Do you just manually download the C code then compile and run gapi-parser? The Source/OldStuff/sources directory appears to contain tools for automating this, but it mentions a Makefile which doesn't exist, and the sources.xml file appears to be configured for gtk2.
- All of the sourceview classes are prefixed with GtkSource, because I have set the namespace to Gtk.Source, which I think makes more sense than GtkSource. Any preferences here?

Resolves #168

### CODE REVIEW

**Comment by Blquinn** [comment]
I noticed that you're using generate.sh to run fixup and codegen, but you're also adding it to the cake build.

The cake build already runs fixup and codegen, so I don't think that's necessary.

It would however, be nice to have a script that runs the parser.

I like the idea of automatically downloading the c source... Could work with a configured version too. I think currently the parsing step has not been committed into the code in this repo at all. (not sure) The way I was attempting to do it was to just leave the .source file there for a reference and let people run the parser when necessary against wherever the c source may be on their system. It would definitely be cool to add the download + parsing to the cake build though.

Anyway, looks good, I will try to run this later today! (I'm on linux too, so idk how much help it will be)

I had the same question about namespaces. I think since this package depends on Gtk, but isn't a part of Gtk, it shouldn't be in the Gtk namespace. Thoughts?

**Comment by Blquinn** [comment]
I get the following exception when trying to run the sample

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Source.GtkSourceView' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Gtk.Source.GtkSourceGutterRendererLines.get_GType() in /home/ben/Code/dotnet/GtkSharpHol/Source/Libs/SourceView/Generated/Gtk.Source/GtkSourceGutterRendererLines.cs:line 52
   at GtkSharp.SourceView.ObjectManager.Initialize() in /home/ben/Code/dotnet/GtkSharpHol/Source/Libs/SourceView/Generated/GtkSharp/ObjectManager.cs:line 30
   at Gtk.Source.GtkSourceView..cctor() in /home/ben/Code/dotnet/GtkSharpHol/Source/Libs/SourceView/Generated/Gtk.Source/GtkSourceView.cs:line 1153
   --- End of inner exception stack trace ---
   at Gtk.Source.GtkSourceView..ctor() in /home/ben/Code/dotnet/GtkSharpHol/Source/Libs/SourceView/Generated/Gtk.Source/GtkSourceView.cs:line 21
   at Samples.MainWindow..ctor() in /home/ben/Code/dotnet/GtkSharpHol/Source/Samples/MainWindow.cs:line 59
   at Samples.Program.Main(String[] args) in /home/ben/Code/dotnet/GtkSharpHol/Source/Samples/Program.cs:line 22
```

**Comment by harry-cpp** [comment]
> * All of the sourceview classes are prefixed with GtkSource, because I have set the namespace to Gtk.Source, which I think makes more sense than GtkSource. Any preferences here?

That's not ok.

> * What is your current process for running gapi-parser to generate the *-api.xml files? Do you just manually download the C code then compile and run gapi-parser? The Source/OldStuff/sources directory appears to contain tools for automating this, but it mentions a Makefile which doesn't exist, and the sources.xml file appears to be configured for gtk2.

I haven't actually connected that part to the CAKE script yet. Yea, you need to download source and run gapi-parser to generate the metadata files.

**Comment by hol430** [comment]
Yeah, the generate script isn't really necessary but I thought it might be useful at least to make it obvious which version of gtksourceview I used to create the -api.xml file that I've committed, for reproducability purposes.

> I get the following exception when trying to run the sample

Hmm, I am getting the same error, although I wasn't getting this the other day, I'll look into it.

Agreed about the namespace thing. I've just changed it to GtkSource which kills 2 birds with 1 stone (removes the GtkSource prefix from generated types), but let me know if you think another name makes more sense.

**Comment by hol430** [comment]
Ok, so it turns out I forgot to hide a few internal datatypes which were causing some problems at runtime. Hiding these as part of the fixup stage seems to fix the error you mentioned above, so if you pull and rerun build.sh it should work.

**Comment by Blquinn** [comment]
Nice, it compiles now!

I found another problem that maybe you have some insight on.

The Buffer in SourceView is a TextView.Buffer, not a SourceView.Buffer. So that needs to get updated.

I made a partial class for SourceView where I add the correct buffer and I now need to add a constructor to initialize the SourceView.Buffer. The problem is that if you hide the constructors in the metatdata file, the generator creates a default protected empty constructor, which doesn't initialize anything. I'm not sure how to override that protected constructor and create my own.

**Comment by hol430** [comment]
I'm not sure I follow, there should already be a constructor available which accepts a GtkSource.Buffer:

image

**Comment by Blquinn** [comment]
@hol430  Yes, but there's no Buffer property on SourceView so its using the TextBuffer from SourceView's base class TextView.

**Comment by hol430** [comment]
Ah I see. Yes, that is kind of annoying although you can still just access it via the Buffer property inherited from TextView and cast the result to a GtkSource.Buffer. This seems to be the recommended practice in the C API. From the [docs](https://developer.gnome.org/gtksourceview/stable/GtkSourceBuffer.html):

> You can also directly create a GtkSourceView and get its GtkSourceBuffer with gtk_text_view_get_buffer().

(gtk_text_view_get_buffer() is inherited from TextView and will return a TextBuffer.)

You can also manually create and keep a handle on the buffer object for later use which can sort of work around the issue:

```csharp
var buffer = new GtkSource.Buffer();
var view = new GtkSource.SourceView(buffer);
...
buffer.HighlightSyntax = true;
```

**Comment by Blquinn** [comment]
Hmm, that's strange, the d and python bindings return the source buffer, not the textbuffer. I don't see a scenario in which we would want it to be the text buffer.

I PR'd into your branch to cast to the sourcebuffer.

**Comment by hol430** [comment]
Makes sense - merged.

On a side note, I've just tested this on windows and it seems to be working ok after installing libgtksourceview4 via msys. Would it be possible to update the dependencies proejct to include sourceview4? (I notice that it already contains sourceview3 but not 4.)

**Comment by harry-cpp** [comment]
> Would it be possible to update the dependencies proejct to include sourceview4?

Yes, it is possible.

**Comment by hol430** [comment]
Sorry, my question wasn't very specific. I will follow this up with the [GTK-for-Windows-Runtime-Environment-Installer](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer) repo, which I assume I'm assuming is where the current set of files in the dependencies project come from. Would you be amenable to a pull request on the dependencies project? 

I note also that the aforementioned project ships glib 2.64.2, so by updating the dependencies we can also fix #172 and #155 at the same time here.

**Comment by hol430** [comment]
Hi @harry-cpp, there's now a new release avilable for the [GTK-for-Windows-Runtime-Environment-Installer](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer) which includes libgtksourceview4 as well as updated glib which should fix the aforementioned issues. I'm happy to make a pull request against the dependencies repo but was wondering if we want to continue to install the files into a directory called %LOCALAPPDATA%\Gtk\3.24\? If we do this then I guess existing users won't receive the update because the directory already will already exist. On the other hand, if we change the directory name, then we will need to synchronise that change with changes to GLibrary.cs and GtkSharp.targets in this repo. Any thoughts?

**Comment by harry-cpp** [comment]
Hold your horses, I'll get around to it in a day or so :)

**Comment by harry-cpp** [comment]
Whats the status on this PR? I'm doing some minor updates and I'll push another update to nuget with updated gtk deps for Windows,

**Comment by hol430** [comment]
Thanks for looking into that. Status on this PR is that it seems to be working ok. I haven't found anything that's definitely broken, although I certainly haven't tried all of the features yet. Mac support probably isn't good, as I'm not sure what the process is for installing libgtksourceview4 on a mac (and don't have a mac to test on).

**Comment by Blquinn** [comment]
I've also used it a bit and found no glaring issues. I'm sure there's a bug or two somewhere, but haven't found one yet.

**Comment by cameronwhite** [comment]
> Thanks for looking into that. Status on this PR is that it seems to be working ok. I haven't found anything that's definitely broken, although I certainly haven't tried all of the features yet. Mac support probably isn't good, as I'm not sure what the process is for installing libgtksourceview4 on a mac (and don't have a mac to test on).

I gave it a try on OSX and just needed to do `brew install gtksourceview4` in order to run the sample application. It looked fine in the sample application (syntax highlighting, line numbers etc showed up)

**Comment by hol430** [comment]
Sweet, thanks for checking that, that's easier than I expected. I guess I might want to update the wiki when this is merged, to include that info.

**Comment by harry-cpp** [comment]
Thanks @hol430 , merging!

**Comment by hol430** [comment]
Hi @harry-cpp, any plans to update the dependencies/nuget packages? No rush or anything, just curious about the status.

**Comment by harry-cpp** [comment]
I was gonna look into a bug on macOS before updating: https://github.com/GtkSharp/GtkSharp/issues/159

**Pull request merged**
