### PR TITLE
Combobox.entry fix invalid cast exception

### PR DESCRIPTION
**Pull request by awittaker**
If a Gtk.ComboBox is created without an Entry, referencing  ComboBox.Entry will generate an InvalidCastType exception since Child in this case is a CellRenderer rather than an Entry.

I've changed it to use 'as' so it will return null if there is no Entry.

I don't think it's worth checking HasEntry property?

Same issue occurs in Gtk.ComboBoxText.Entry.
In this case, ComboBoxText.Entry is actually hiding ComboBox.Entry, so since they are currently identical, I've just removed ComboBoxText.Entry so it inherits it from ComboBox instead.

### CODE REVIEW

**Comment by cra0zy** [comment]
Use `Gtk.Entry?` instead of `Gtk.Entry`, that way we tell the dev: "this can be null so be carefull"

**Comment by awittaker** [comment]
Not sure I follow - Gtk.Entry is not a value type?

**Comment by cra0zy** [comment]
Oh yea, that's only a C# 8 thingy. Kinda forgot about that. Merging!

PS. In case you are wondering what I'm talking about: https://docs.microsoft.com/en-us/archive/msdn-magazine/2018/february/essential-net-csharp-8-0-and-nullable-reference-types

**Comment by awittaker** [comment]
Thanks Cra0zy - C# 8.0 looks good.
Of course, now I have to ask when GtkSharp will adopt .NET Standard 2.1 !!

**Pull request merged**
