### PR TITLE
GLibrary.cs: introduce IsSupported

### PR DESCRIPTION
**Pull request by lytico**
There is the possibility that some libraries are not supported, cause they are not installed.

This problem arise eg. with GtkSourceView, and, in future, with Webkit and other non-standard Gtk Libraries.

With this PR there with

GLibrary.IsSupported(Library)

the library support can be checked before running into a DllNotFound-Exception

### CODE REVIEW

**Comment by lytico** [comment]
@zii-dmg would be nice if you review that.

**Comment by zii-dmg** [comment]
GLibray is not for public usage, doesn't have namespace and don't have public modifier. I don't know if we should change that.

**Comment by zii-dmg** [comment]
There is Global classes in many libs (Gtk.Global, Pango.Global). We can create that class for every lib and add property `IsLibraryAvailable` / `IsLibrarySupported`.

**Comment by lytico** [comment]
> We can create that class for every lib and add property IsLibraryAvailable / IsLibrarySupported.

or add that manual, just a few lines.

**Comment by zii-dmg** [comment]
This is what I meant, yes. Manually add property to (existing or new) class `Global` in every lib. Or better - not in all libs but in libs that can be unsupported - GtkSourceView and GtkWebKit.

**Comment by lytico** [comment]
have done it everywhere. who knows if there is the need of extending this feature.

**Comment by zii-dmg** [comment]
Ok.

**Pull request merged**
